# Postgresql connection string
databaseURL = "user=klpuser password=klppassword_example dbname=klpdb_example host=postgresdb port=5432 sslmode=disable"

# trace / debug / info /  error / panic
log_level = "trace"

# All intervals and timeouts are set in seconds
[linesProvider]
    address = "http://linesprovider:8000"
    requestsTimeout = 15
    syncInterval_baseball = 5
    syncInterval_football = 5
    syncInterval_soccer  = 5
[HTTPAPI]
    address = "0.0.0.0:8080"
    readTimeout = 5
    writeTimeout = 5
[gRPC]
    address = "0.0.0.0:8081"